services:
  db_postgres:
    image: postgres:16-alpine
    container_name: orion_postgres_db
    environment:
      POSTGRES_USER: orion_user
      POSTGRES_PASSWORD: orion_password
      POSTGRES_DB: orion_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "orion_user", "-d", "orion_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [orion_network]

  db_mongo:
    image: mongo:latest
    container_name: orion_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: orion_admin
      MONGO_INITDB_ROOT_PASSWORD: orion_admin_pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [orion_network]

  mongo_client:
    build:
      context: ./exercicio-4
      dockerfile: Dockerfile.dev
    container_name: orion_mongo_client_dev
    depends_on:
      - db_mongo
    volumes:
      - ./exercicio-4/scripts:/app/scripts
    command: >
      mongosh mongodb://orion_admin:orion_admin_pass@db_mongo:27017/?authSource=admin /app/scripts/queries.js
    networks: [orion_network]

volumes:
  postgres_data:
  mongo_data:

networks:
  orion_network:
    driver: bridge
